package com.compliance.forensics.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.compliance.forensics.data.database.AuditLogEntity
import com.compliance.forensics.data.repository.AuditRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Locale

class AuditViewModel(
    private val repository: AuditRepository
) : ViewModel() {

    val allLogs: Flow<List<AuditLogEntity>> = repository.getAllLogs()

    private val _statistics = MutableStateFlow<AuditRepository.AuditStatistics?>(null)
    val statistics: StateFlow<AuditRepository.AuditStatistics?> = _statistics.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _exportResult = MutableStateFlow<String?>(null)
    val exportResult: StateFlow<String?> = _exportResult.asStateFlow()

    init {
        loadStatistics()
    }

    fun loadStatistics() {
        viewModelScope.launch {
            _isLoading.value = true
            try {
                _statistics.value = repository.getStatistics()
            } finally {
                _isLoading.value = false
            }
        }
    }

    fun refreshStatistics() {
        loadStatistics()
    }

    fun getLogsByStatus(status: String): Flow<List<AuditLogEntity>> {
        return repository.getLogsByStatus(status)
    }

    fun exportLogAsProof(logId: Long) {
        viewModelScope.launch {
            _isLoading.value = true
            try {
                val log = repository.getLogById(logId)
                if (log != null) {
                    val proof = generateExportProof(log)
                    repository.markAsExported(logId)
                    _exportResult.value = proof
                } else {
                    _exportResult.value = "Error: Log not found"
                }
            } catch (e: Exception) {
                _exportResult.value = "Error: ${e.message}"
            } finally {
                _isLoading.value = false
            }
        }
    }

    private fun generateExportProof(log: AuditLogEntity): String {
        return """
            ===========================================
            COMPLIANCE FORENSICS ENGINE - AUDIT PROOF
            ===========================================
            
            Caller ID: ${log.callerId}
            Caller Name: ${log.callerName}
            Verification Status: ${log.verificationStatus}
            Timestamp: ${log.getFormattedTimestamp()}
            
            Consent Hash: ${log.consentHash}
            Audit Proof Hash: ${log.auditProofHash}
            
            --------------------------------------------------
            VERIFICATION DETAILS
            --------------------------------------------------
            This proof was generated on-device using SHA-256
            cryptographic hashing. The hash represents:
            
            Paudt = Hash(IDcaller || Consent || t)
            
            Where:
            - IDcaller: ${log.callerId}
            - Consent: ${log.consentHash}
            - t: ${log.timestamp}
            
            --------------------------------------------------
            LEGAL VALIDITY
            --------------------------------------------------
            This record complies with:
            - TRAI DLT Regulations
            - RBI DCA Pilot Requirements
            - TCCCPR 2018 Guidelines
            - IT SPDI Rules (Privacy Compliant)
            
            Generated by: Compliance Forensics Engine v1.0
            Export Time: ${SimpleDateFormat("dd/MM/yyyy HH:mm:ss", Locale.getDefault()).format(System.currentTimeMillis())}
            ===========================================
        """.trimIndent()
    }

    fun clearExportResult() {
        _exportResult.value = null
    }
}